FONT_EXCEPTIONS = {
    'ABeeZee': 'ABeeZee',
    'AlegreyaSC': 'Alegreya SC',
    'AlegreyaSansSC': 'Alegreya Sans SC',
    'AlmendraSC': 'Almendra SC',
    'AmaticSC': 'Amatic SC',
    'AmaticaSC': 'Amatica SC',
    'BowlbyOneSC': 'Bowlby One SC',
    'CarroisGothicSC': 'Carrois Gothic SC',
    'CormorantSC': 'Cormorant SC',
    'DiplomataSC': 'Diplomata SC',
    'EBGaramond': 'EB Garamond',
    'GFSDidot': 'GFS Didot',
    'GFSNeohellenic': 'GFS Neohellenic',
    'HoltwoodOneSC': 'Holtwood One SC',
    'IMFellDWPica': 'IM Fell DW Pica',
    'IMFellDWPicaSC': 'IM Fell DW Pica SC',
    'IMFellDoublePica': 'IM Fell Double Pica',
    'IMFellDoublePicaSC': 'IM Fell Double Pica SC',
    'IMFellEnglish': 'IM Fell English',
    'IMFellEnglishSC': 'IM Fell English SC',
    'IMFellFrenchCanon': 'IM Fell French Canon',
    'IMFellFrenchCanonSC': 'IM Fell French Canon SC',
    'IMFellGreatPrimer': 'IM Fell Great Primer',
    'IMFellGreatPrimerSC': 'IM Fell Great Primer SC',
    'MarcellusSC': 'Marcellus SC',
    'MateSC': 'Mate SC',
    'NTR': 'NTR',
    'OldStandardTT': 'Old Standard TT',
    'OverlockSC': 'Overlock SC',
    'PTMono': 'PT Mono',
    'PTSans': 'PT Sans',
    'PTSansCaption': 'PT Sans Caption',
    'PTSansNarrow': 'PT Sans Narrow',
    'PTSerif': 'PT Serif',
    'PTSerifCaption': 'PT Serif Caption',
    'PatrickHandSC': 'Patrick Hand SC',
    'PlayfairDisplaySC': 'Playfair Display SC',
    'VollkornSC': 'Vollkorn SC',
    'VT323': 'VT323',
}
